### PR TITLE
Fix public assets not in iso

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
This goes with https://github.com/kubic-project/caasp-container-manifests/pull/192

**Comment by jordimassaguerpla** [comment]
also with https://github.com/kubic-project/velum/pull/579

**Comment by MaximilianMeister** [comment]
i think we should keep the static pages here in this repo and drop them from velum instead

otherwise we'll have to change it again should we decide to have a different color scheming for example

**Comment by MaximilianMeister** [comment]
the static error pages are not precompiled btw, so i guess the issue are only the images and the stylesheets?

**Pull request merged**
